### ISSUE TITLE
How to get test set predictions?

### ISSUE THREAD

**Issue by aflah02** [wenliangdai/multi-task-offensive-language-detection#1]
Hi!
First of all great work and thanks for the easily readable code 
I was trying to recreate the results and was able to train the model but I can't seem to find any instructions to use the save files to perform inference. Can you share some instructions for the same?

**Comment by aflah02** [comment]
I tried running `python prediction_generator.py --task a --model bert --batch-size 32 --learning-rate 0.0001 --epochs 10` but I get this error 

```
  0%|                                                                                                                    | 0/27 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prediction_generator.py", line 136, in <module>
    y_pred_A = all_logits[0].argmax(dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

If I try to change the dimension to -1 or 0 I get - 

```
  0%|                                                                                                                    | 0/27 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prediction_generator.py", line 146, in <module>
    line.append('OFF' if y_pred_A[i] == 0 else 'NOT')
TypeError: 'int' object is not subscriptable
```

I'm using the model saved here - `multi-task-offensive-language-detection/save/models/a_bert_0.8136770488410596_seed19951126.pt`

**Comment by aflah02** [comment]
Eventually wrote a custom script to load from checkpoint and evaluate couldn't get the file to work but the checkpoints are good
